export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const WAITING_TO_FETCH = "WAITING_TO_FETCH";
export const ANIMALS_FETCHED = "ANIMALS_FETCHED";
export const GET_ALL_ANIMALS = "GET_ALL_ANIMALS";
export const CHANGE_PAGE = "CHANGE_PAGE";

export const OPERATION_USER_BEGIN = "OPERATION_USER_BEGIN";
export const REGISTER_USER_OK = "REGISTER_USER_OK";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGIN_USER_OK = "LOGIN_USER_OK";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
